### ISSUE TITLE
Apotheosis attribute damage is only displayed once

### ISSUE THREAD

**Issue by Dr-WeiAL** [MehVahdJukaar/DuMmmMmmy1.16#3]
As mentioned above
When using a weapon with Apotheosis damage to attack the dummy, the normal damage will be displayed for the first time, but after that, only the damage of the weapon itself will be displayed. 

![image](https://user-images.githubusercontent.com/47446553/141693015-363eba8b-385f-4c38-a553-ed531cb4f33b.png)

This is the first attack
![image](https://user-images.githubusercontent.com/47446553/141692850-77cd1e31-9ff5-4c4b-a07e-f8b89ebcfb29.png)

This is the attack after the first time
![image](https://user-images.githubusercontent.com/47446553/141692884-dc15594e-7725-4a6d-a1ba-9c29dbd53831.png)

**Comment by MehVahdJukaar** [comment]
does it still happen with latest version?

**Comment by Dr-WeiAL** [comment]
> does it still happen with latest version?

Apotheosis has not updated the version above 1.16.5 and cannot be tested. If it is the latest version of 1.16.5, it still does not work.

**Comment by Dr-WeiAL** [comment]
Oh well this issues is still open now ah
I think this problem should have been solved
So I'll close it
![image](https://user-images.githubusercontent.com/47446553/192116232-68ba0cd0-f7ac-4657-b052-7955bd46c172.png)
