### ISSUE TITLE
Missing features when used on a server together with lithium

### ISSUE THREAD

**Issue by 2No2Name** [MehVahdJukaar/DuMmmMmmy1.16#6]
According to one lithium user there are mod compatibility problems:

https://github.com/CaffeineMC/lithium-fabric/issues/322

I have not tried to verify their findings on my own:

> ###Version / Mods Used:
> Lithium mc1.18.1-0.7.6
> MmmMmmMmmMmm-1.18-1.5.0-FABRIC    https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm/files
> Fabric Api 0.44.0+1.18
> 
> ### Expected Behavior
> 
> The target dummy usually makes a special sound, shows the dealt dmg from every single hit as numbers flying away from the dummys head and shows a dmg/s counter above the hotbar when hit. 
> ### Actual Behavior
> In single player with lithium installed on the client everything works fine, but on a dedicated server with lithium installed on the server all those features are missing and only the hitting animation is left.
> 
> ### Reproduction Steps
> 
> 1. Start a dedicated server with MmmMmmMmmMmm and Lithium installed
> 2. Place down the Target Dummy
> 3. Hit the Target Dummy

**Comment by MehVahdJukaar** [comment]
No idea what's causing this. I'll try to install lithium on my Dev environment and try to see what is not getting fired. Also I haven't updated the GitHub project here in a while so I'll update that too even if the changes between forge and fabric versions are very minimal

**Comment by MehVahdJukaar** [comment]
Actually I already have fabric version here https://github.com/MehVahdJukaar/DummyFabric1.16

**Comment by Chuunkyz** [comment]
hey, will the lithium incompatibility be fixed at some point ? every fabric modpack has lithium, we can't use ur mod on servers right now...

**Comment by MehVahdJukaar** [comment]
from what I know I'm not doing anything to directly conflict with lithium and from my point of view its a problem from their end since it does impede some of the functionality of my mod. I've tried looking at it but I didnt manage to find out what was going wrong. If you want this to be fixed sooner feel free to bump this issue here  which I'm still waiting for a relpy https://github.com/CaffeineMC/lithium-fabric/issues/322

**Comment by MehVahdJukaar** [comment]
Should have been fixed, at least the crash that is
