### ISSUE TITLE
Player Skin

### ISSUE THREAD

**Issue by syorito-hatsuki** [MehVahdJukaar/DuMmmMmmy1.16#9]
What about, if dummy can get player skin by renaming on Anvil?)

**Comment by MehVahdJukaar** [comment]
That wouldnt work since dummies have a different model that players. First of all they have shorter arms second it will break for slim skins

**Comment by syorito-hatsuki** [comment]
> That wouldnt work since dummies have a different model that players. First of all they have shorter arms second it will break for slim skins
What about if only head for start :D ?

**Comment by MehVahdJukaar** [comment]
Well you could pretty much do that by equipping them with a playerhead

**Comment by syorito-hatsuki** [comment]
Other player head in single player?)
